/**
 * Corex — ESLint flat config.
 *
 * This file exists for one reason: scope. `wp-scripts lint-js` with no project config lints `.`
 * under the default config, whose global ignores are only `**\/build/**`, `**\/node_modules/**`
 * and `**\/vendor/**`. This repository also contains a full WordPress install at `wp/` and the
 * generated shared-host bundle at `dist/`, so the default run walked tens of thousands of files
 * that are not ours and never terminated in practice — which is why `lint:js` was never gated in
 * CI while `lint:css` (which has `.stylelintignore`) always could be. The ignore list below is the
 * `.stylelintignore` list, so both linters see exactly the same tree.
 *
 * Providing any `eslint.config.*` makes wp-scripts stop passing its own `--config`, so the
 * WordPress defaults have to be re-exported here rather than inherited implicitly.
 */

const wpScriptsConfig = require( '@wordpress/scripts/config/eslint.config.cjs' );

module.exports = [
	{
		ignores: [
			'**/node_modules/**',
			'**/vendor/**',
			'**/build/**',
			'**/dist/**',
			'wp/**',
			// Generated by the browser suite, not authored here.
			'playwright-report/**',
			'test-results/**',
			'coverage/**',
			// Astro's generated type shims.
			'docs-app/.astro/**',
		],
	},
	...wpScriptsConfig,
];
