/**
 * The repository states one version, tracks no generated clutter, and keeps its root readable.
 *
 * Everything here is asserted against **what git actually tracks**, not against the working tree.
 * The distinction is the point: a `.gitignore` rule tells you what git was *asked* to skip, and this
 * asks what it *kept*. Spec 097 lost a fixture to a glob that was doing its job — a `fix` wildcard
 * under `tests/e2e`, there for throwaway render output, which also swallowed `tests/e2e/fixtures`.
 * The only symptom until CI ran was a commit that looked complete.
 *
 * The three checks are the three ways this repository has actually drifted:
 *
 *   1. Generated or exported files reaching the index, where they rot and bloat clones.
 *   2. Root Markdown accumulating until the canonical set is no longer findable in it.
 *   3. A version declared in prose disagreeing with `package.json`, or a document announcing a
 *      release that has no tag — which is exactly the state this repository was in before v0.41.0
 *      (`PROGRESS.md` opened with "v0.41.0 released" while the newest tag was v0.40.0).
 *
 * Deliberately permissive about specs, evidence, translations and documentation: those are the
 * record this project is built on, and a hygiene guard that fought them would be turned off.
 */
const { execFileSync } = require( 'node:child_process' );
const fs = require( 'node:fs' );
const path = require( 'node:path' );

const repositoryRoot = path.resolve( __dirname, '..' );

const {
	loadOwnership,
	resolveRole,
} = require( '../scripts/repository-ownership.mjs' );

/** The `origin` remote, or an empty string where there is none. */
const originUrl = ( () => {
	try {
		return execFileSync(
			'git',
			[ '-C', repositoryRoot, 'remote', 'get-url', 'origin' ],
			{ encoding: 'utf8', stdio: [ 'ignore', 'pipe', 'ignore' ] }
		).trim();
	} catch {
		return '';
	}
} )();

/** `framework` in CoreX's own repository, `client` in a repository built on it (spec 102). */
const repositoryRole = resolveRole( {
	ownership: loadOwnership( repositoryRoot ),
	env: process.env,
	originUrl,
} );

/** Every path git tracks, one per line. */
const trackedFiles = execFileSync(
	'git',
	[ '-C', repositoryRoot, 'ls-files' ],
	{
		encoding: 'utf8',
		maxBuffer: 32 * 1024 * 1024,
	}
)
	.split( /\r?\n/ )
	.filter( Boolean );

/**
 * What must never be tracked, and the reason, so a failure explains itself.
 *
 * Each entry is matched against the full repository-relative path.
 */
const FORBIDDEN = [
	[ /^dist\/|\/dist\//, 'build output — generated by npm run build:dist' ],
	[ /^build\/|\/build\//, 'build output — generated by npm run build' ],
	[
		/^wp(?:-ms)?\//,
		'a local WordPress install — the monorepo is the source, wp/ and wp-ms/ are runtime',
	],
	[
		/^vendor\/|\/vendor\//,
		'Composer dependencies — install from composer.lock',
	],
	[
		/^node_modules\/|\/node_modules\//,
		'npm dependencies — install from package-lock.json',
	],
	[ /^output\//, 'ad-hoc local script output' ],
	[ /^test-results\/|\/test-results\//, 'Playwright run output' ],
	[
		/^playwright-report\/|\/playwright-report\//,
		'Playwright report output',
	],
	[
		/\.zip$|\.tar\.gz$|\.tgz$|\.rar$|\.7z$/,
		'an archive — ship releases, not committed archives',
	],
	[ /\.dc\.html$/, 'a raw design-tool export' ],
	[ /\.(bak|orig|swp|tmp)$|~$/, 'an editor or backup artifact' ],
	[ /(^|\/)(\.DS_Store|Thumbs\.db|desktop\.ini)$/, 'an OS artifact' ],
	[
		/(^|\/)\.env(\.|$)/,
		'an environment file — only .env.example belongs in git',
	],
	[
		/(^|\/)(id_rsa|id_ed25519)$|\.pem$|\.p12$|\.pfx$/,
		'a private key or certificate',
	],
];

/**
 * What must never be tracked in the framework's own repository, and may be in a client's.
 *
 * `sites/<client>/` is where `make:site` puts a client site, and a client's repository is built
 * around one. This rule used to sit in the list above and applied everywhere, so it failed the
 * suite on the client's own deliverable and the client had to delete it — an edit to a framework
 * file, and so a conflict waiting in every later update (spec 102). It is now a statement about
 * one repository rather than about all of them. Every rule above still applies inside `sites/`.
 */
const FORBIDDEN_IN_THE_FRAMEWORK = [
	[
		/^sites\//,
		'a client site implementation — those live in their own repository',
	],
];

/**
 * Whether a file is the helper a design tool writes beside its export.
 *
 * It is called `support.js`, which is also a reasonable name for anybody's own file. So it is the
 * helper only where an export is: at the root, under `design/`, or in a directory that holds a
 * `.dc.html`.
 *
 * @param {string}   file  One repository-relative path.
 * @param {string[]} files Every path it is tracked beside.
 * @return {boolean} True for a design-export helper.
 */
const isDesignExportHelper = ( file, files ) => {
	if ( path.posix.basename( file ) !== 'support.js' ) {
		return false;
	}
	const directory = path.posix.dirname( file );

	return (
		directory === '.' ||
		/^design(\/|$)/.test( directory ) ||
		files.some(
			( other ) =>
				other.endsWith( '.dc.html' ) &&
				path.posix.dirname( other ) === directory
		)
	);
};

/** `.env.example` is the deliberate exception to the `.env` rule. */
const FORBIDDEN_EXCEPTIONS = [ /(^|\/)\.env\.example$/ ];

/**
 * Every tracked path that must not be tracked, with the reason, for a repository in `role`.
 *
 * @param {string[]} files Repository-relative paths.
 * @param {string}   role  `framework` or `client`.
 * @return {string[]} One sentence per offender.
 */
const offendersIn = ( files, role ) => {
	const rules =
		role === 'framework'
			? [ ...FORBIDDEN, ...FORBIDDEN_IN_THE_FRAMEWORK ]
			: FORBIDDEN;

	return files
		.filter(
			( file ) =>
				! FORBIDDEN_EXCEPTIONS.some( ( allowed ) =>
					allowed.test( file )
				)
		)
		.flatMap( ( file ) => {
			const match = rules.find( ( [ pattern ] ) => pattern.test( file ) );
			if ( match ) {
				return [ `${ file } — ${ match[ 1 ] }` ];
			}

			return isDesignExportHelper( file, files )
				? [ `${ file } — a design-export helper script` ]
				: [];
		} );
};

/**
 * The Markdown files allowed to sit at the repository root.
 *
 * A closed list, not a pattern. The root is the first thing a reader sees, and the failure mode this
 * prevents is not one bad file — it is twenty plausible ones, each of which looked reasonable on the
 * day it was added. A new root document is a deliberate decision, so it should cost one line here.
 */
const ALLOWED_ROOT_MARKDOWN = [
	'AGENTS.md',
	'CHANGELOG.md',
	'CLAUDE.md',
	'CODE_OF_CONDUCT.md',
	'CONTRIBUTING.md',
	'DECISIONS.md',
	'PROGRESS.md',
	'PROJECT-STATUS.md',
	'README.md',
	'ROADMAP.md',
	'SECURITY.md',
];

describe( 'tracked files', () => {
	it( 'holds no generated directory, archive, export or secret', () => {
		expect( offendersIn( trackedFiles, repositoryRole ) ).toEqual( [] );
	} );

	it( 'keeps the repository root to its canonical documents', () => {
		const rootMarkdown = trackedFiles
			.filter( ( file ) => /^[^/]+\.mdx?$/.test( file ) )
			.sort();

		expect( rootMarkdown ).toEqual( ALLOWED_ROOT_MARKDOWN );
	} );

	it( 'keeps every canonical document present', () => {
		// The inverse of the check above, and not redundant with it: an equality assertion fails
		// identically whether a file was added or deleted, and "README.md is missing" deserves to be
		// said in those words rather than inferred from a diff of two lists.
		const missing = ALLOWED_ROOT_MARKDOWN.filter(
			( file ) => ! fs.existsSync( path.join( repositoryRoot, file ) )
		).map( ( file ) => `${ file } is missing from the repository root` );

		expect( missing ).toEqual( [] );
	} );
} );

describe( 'a client site under sites/', () => {
	const clientSite = [
		'sites/acme/AGENTS.md',
		'sites/acme/acme-site/acme-site.php',
		'sites/acme/acme-theme/theme.json',
	];

	it( 'is refused in the framework repository', () => {
		expect( offendersIn( clientSite, 'framework' ) ).toEqual(
			clientSite.map(
				( file ) =>
					`${ file } — a client site implementation — those live in their own repository`
			)
		);
	} );

	it( 'is accepted in a client repository', () => {
		expect( offendersIn( clientSite, 'client' ) ).toEqual( [] );
	} );

	it.each( [
		[ 'sites/acme/.env', 'an environment file' ],
		[ 'sites/acme/handoff.zip', 'an archive' ],
		[ 'sites/acme/acme-theme/build/main.js', 'build output' ],
		[
			'sites/acme/acme-site/node_modules/left-pad/index.js',
			'npm dependencies',
		],
		[ 'sites/acme/acme-site/vendor/autoload.php', 'Composer dependencies' ],
		[ 'sites/acme/deploy.pem', 'a private key or certificate' ],
	] )( 'still refuses %s in a client repository', ( file, reason ) => {
		const offenders = offendersIn( [ file ], 'client' );

		expect( offenders ).toHaveLength( 1 );
		expect( offenders[ 0 ] ).toContain( reason );
	} );
} );

/**
 * `support.js` is the helper a design tool writes beside its `.dc.html` export. The rule refused
 * every file of that name, anywhere, and it is also what a client called its own Playwright helper:
 * the first client site had "Lint + JS unit tests" fail on two pull requests over a test file of its
 * own (2026-10-07). It is refused where an export is, and nowhere else.
 */
describe( 'a file named support.js', () => {
	it.each( [
		[ 'at the repository root', [ 'support.js' ] ],
		[ 'under design/', [ 'design/handoff/support.js' ] ],
		[
			'beside a design export',
			[ 'docs/mockups/Inbox.dc.html', 'docs/mockups/support.js' ],
		],
	] )( 'is refused as a design-export helper %s', ( _where, files ) => {
		expect( offendersIn( files, 'client' ) ).toContain(
			`${ files[ files.length - 1 ] } — a design-export helper script`
		);
	} );

	it.each( [
		[ 'sites/acme/acme-site/tests/e2e/support.js' ],
		[ 'tests/e2e/support.js' ],
		[ 'plugins/corex-config/src/admin/support.js' ],
	] )( 'is a file like any other at %s', ( file ) => {
		expect( offendersIn( [ file ], 'client' ) ).toEqual( [] );
	} );

	it( 'is not excused by a design export somewhere else', () => {
		expect(
			offendersIn(
				[ 'docs/mockups/Inbox.dc.html', 'tests/e2e/support.js' ],
				'client'
			)
		).toEqual( [
			'docs/mockups/Inbox.dc.html — a raw design-tool export',
		] );
	} );
} );

describe( 'the version the repository claims', () => {
	const declaredVersion = JSON.parse(
		fs.readFileSync( path.join( repositoryRoot, 'package.json' ), 'utf8' )
	).version;

	/**
	 * Where prose states the *current* version, and the pattern that captures it.
	 *
	 * These mirror `Corex\Cli\Release\VersionPlan::PROSE_PATTERNS`, which is what `wp corex version`
	 * stamps. Two lists that must agree is a smell, and it is the lesser one: the stamper is PHP and
	 * runs at release time, this is JavaScript and runs on every pull request. What this catches is a
	 * document edited by hand between releases, which is precisely how these drifted before the
	 * stamper existed.
	 */
	const CURRENT_VERSION_CLAIMS = [
		[ 'README.md', /^## Status: v(\d+\.\d+\.\d+),/m ],
		[ 'README.md', /^wp corex readiness (\d+\.\d+\.\d+)$/m ],
		[ 'ROADMAP.md', /^\*\*Currently released: v(\d+\.\d+\.\d+)\.\*\*/m ],
		[ 'PROJECT-STATUS.md', /^\*\*Version (\d+\.\d+\.\d+)\*\* ·/m ],
	];

	it.each( CURRENT_VERSION_CLAIMS )(
		'%s agrees with package.json',
		( file, pattern ) => {
			const contents = fs.readFileSync(
				path.join( repositoryRoot, file ),
				'utf8'
			);
			const found = contents.match( pattern );

			// A missing anchor is a failure, not a pass. If the sentence is reworded, `wp corex
			// version` stops stamping it silently and the file drifts from the next release onward —
			// so the absence is reported as its own sentence rather than as `null !== '0.41.0'`.
			expect(
				found === null
					? `${ file } no longer carries the sentence the release stamper anchors to: ${ pattern }`
					: found[ 1 ]
			).toBe( declaredVersion );
		}
	);

	it( 'never announces a release that has no tag', () => {
		const tags = new Set(
			execFileSync( 'git', [ '-C', repositoryRoot, 'tag', '--list' ], {
				encoding: 'utf8',
				maxBuffer: 8 * 1024 * 1024,
			} )
				.split( /\r?\n/ )
				.filter( Boolean )
		);

		// Only the present tense. "released as v0.38.1" in a changelog is a true statement about the
		// past; "v0.41.0 released" at the top of a status file, with no v0.41.0 tag anywhere, is the
		// claim this repository actually made and the one worth failing on.
		const announcement = /\bv?(\d+\.\d+\.\d+)\s+(?:is\s+)?released\b/gi;
		const offenders = [];

		for ( const file of [
			'README.md',
			'PROGRESS.md',
			'PROJECT-STATUS.md',
		] ) {
			const contents = fs.readFileSync(
				path.join( repositoryRoot, file ),
				'utf8'
			);

			for ( const match of contents.matchAll( announcement ) ) {
				if ( ! tags.has( `v${ match[ 1 ] }` ) ) {
					offenders.push(
						`${ file }: claims ${ match[ 0 ] }, but no tag v${ match[ 1 ] } exists`
					);
				}
			}
		}

		expect( offenders ).toEqual( [] );
	} );
} );

describe( 'the docs-site mirror of the project status', () => {
	it( 'is regenerated from PROJECT-STATUS.md rather than maintained by hand', () => {
		// The same contract `tests/token-inventory.test.js` holds the token inventory to: a generated
		// artifact is committed so the site builds and the diff is reviewable, and a test regenerates
		// it to prove nobody edited the copy instead of the source. Two hand-kept copies of a status
		// page is how one of them ends up describing a release the other does not.
		const {
			renderProjectStatusPage,
		} = require( '../scripts/sync-project-status.mjs' );

		const generated = renderProjectStatusPage( repositoryRoot );
		const committed = fs.readFileSync(
			path.join(
				repositoryRoot,
				'docs-app/src/content/docs/project-status.md'
			),
			'utf8'
		);

		expect( committed ).toBe( generated );
	} );
} );

describe( "Spec Kit in a repository that is not only the framework's", () => {
	/**
	 * In a client repository everything outside `sites/` is the framework's, and a change there is
	 * drift (spec 102). Running the documented Spec Kit workflow made two such changes on its own:
	 * `/speckit-specify` wrote the feature it was working on into `.specify/feature.json`, which
	 * was tracked, and the agent-context hook rewrote a section of the root `CLAUDE.md` (#251).
	 *
	 * Where a spec lives was never the problem: Spec Kit takes the directory it is given.
	 */
	it( 'keeps the feature being worked on out of the tree', () => {
		const tracked = execFileSync(
			'git',
			[ 'ls-files', '--', '.specify/feature.json' ],
			{ cwd: repositoryRoot, encoding: 'utf8' }
		).trim();
		const ignored = execFileSync(
			'git',
			[ 'check-ignore', '.specify/feature.json' ],
			{ cwd: repositoryRoot, encoding: 'utf8' }
		).trim();

		expect( tracked ).toBe( '' );
		expect( ignored ).toBe( '.specify/feature.json' );
	} );

	it( 'runs no hook that rewrites an agent instruction file', () => {
		const extensions = fs.readFileSync(
			path.join( repositoryRoot, '.specify', 'extensions.yml' ),
			'utf8'
		);
		// Each hook is a list item; one that is on says `enabled: true`.
		const hooksLeftOn = extensions
			.split( /^\s*- extension:/m )
			.slice( 1 )
			.filter( ( hook ) => /^\s*enabled:\s*true\s*$/m.test( hook ) )
			.map( ( hook ) => hook.match( /command:\s*(\S+)/ )[ 1 ] );

		expect( hooksLeftOn ).toEqual( [] );
		expect(
			fs.readFileSync( path.join( repositoryRoot, 'CLAUDE.md' ), 'utf8' )
		).not.toContain( 'SPECKIT START' );
	} );
} );

describe( 'what each release says to a client site', () => {
	/**
	 * A client repository takes a release by merging it, and a clean merge proves less than it
	 * looks like. v0.40.0 changed three behaviours a client depended on and v0.41.0 removed a
	 * package a client build had been borrowing; both merged without a conflict, with every suite
	 * green, and both were found afterwards by hand (spec 102).
	 *
	 * So each release states, under one reserved heading, what in it can change a client site's
	 * behaviour — and a release with nothing to state says that, because an absent heading reads
	 * exactly like "nobody checked".
	 */
	const HEADING = '### Client impact';
	const FIRST_RELEASE_HELD_TO_IT = [ 0, 43, 0 ];

	const changelog = fs.readFileSync(
		path.join( repositoryRoot, 'CHANGELOG.md' ),
		'utf8'
	);

	/** Each `## [name]` section, as its name and everything up to the next one. */
	const sections = changelog
		.split( /^(?=## \[)/m )
		.filter( ( section ) => section.startsWith( '## [' ) )
		.map( ( section ) => ( {
			name: section.match( /^## \[([^\]]+)\]/ )[ 1 ],
			body: section.replace( /^## \[[^\n]*\n/, '' ),
		} ) );

	const isHeldToIt = ( name ) => {
		const version = name.split( '.' ).map( Number );

		for ( let part = 0; part < FIRST_RELEASE_HELD_TO_IT.length; part++ ) {
			if ( version[ part ] !== FIRST_RELEASE_HELD_TO_IT[ part ] ) {
				return version[ part ] > FIRST_RELEASE_HELD_TO_IT[ part ];
			}
		}

		return true;
	};

	it( 'reads the changelog the way it is written', () => {
		// A guard against going quiet: if the section pattern stopped matching, the assertions
		// below would pass over nothing.
		expect( sections.map( ( { name } ) => name ) ).toEqual(
			expect.arrayContaining( [ 'Unreleased', '0.42.0' ] )
		);
		expect( isHeldToIt( '0.42.0' ) ).toBe( false );
		expect( isHeldToIt( '0.43.0' ) ).toBe( true );
		expect( isHeldToIt( '1.0.0' ) ).toBe( true );
	} );

	it( 'has a Client impact section in every release from 0.43.0 on', () => {
		const missing = sections
			.filter( ( { name } ) => /^\d+\.\d+\.\d+$/.test( name ) )
			.filter( ( { name } ) => isHeldToIt( name ) )
			.filter( ( { body } ) => ! body.includes( HEADING ) )
			.map( ( { name } ) => name );

		expect( missing ).toEqual( [] );
	} );

	it( 'has one under Unreleased as soon as anything is written there', () => {
		const unreleased = sections.find(
			( { name } ) => name === 'Unreleased'
		);
		const says = unreleased.body.trim() !== '';

		expect( says && ! unreleased.body.includes( HEADING ) ).toBe( false );
	} );
} );

/**
 * A control whose request is on its way looks one way across the admin (spec 108, FR-020): the
 * CoreX loader over a button that keeps its width, from `workingProps`. `isBusy` is WordPress's
 * own answer, a striped button in WordPress's colours, and four screens had it while others
 * changed their label or showed nothing. It is not a lint rule because nothing is wrong with the
 * prop itself; it is wrong here.
 */
describe( "WordPress's striped busy button", () => {
	it( 'is not what an admin screen shows while it works', () => {
		const users = trackedFiles
			.filter(
				( file ) =>
					/^plugins\/corex-config\/src\/.+\.js$/.test( file ) &&
					! file.includes( '/__tests__/' )
			)
			.filter( ( file ) =>
				/\bisBusy\b/.test(
					fs.readFileSync( path.join( repositoryRoot, file ), 'utf8' )
				)
			);

		expect( users ).toEqual( [] );
	} );

	// The same for a wait (spec 108, FR-001): a placeholder in the shape of what is coming, from
	// `CorexLoadable`, where WordPress's spinner beside a sentence used to be. The inbox and its
	// pane were the last two to have one.
	it( 'has no spinner beside it either', () => {
		const users = trackedFiles
			.filter(
				( file ) =>
					/^plugins\/corex-config\/src\/.+\.js$/.test( file ) &&
					! file.includes( '/__tests__/' )
			)
			.filter( ( file ) =>
				/\bSpinner\b/.test(
					fs.readFileSync( path.join( repositoryRoot, file ), 'utf8' )
				)
			);

		expect( users ).toEqual( [] );
	} );
} );
